/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GrupoRouteImport } from './routes/grupo'
import { Route as IndexRouteImport } from './routes/index'

const GrupoRoute = GrupoRouteImport.update({
  id: '/grupo',
  path: '/grupo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/grupo': typeof GrupoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/grupo': typeof GrupoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/grupo': typeof GrupoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/grupo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/grupo'
  id: '__root__' | '/' | '/grupo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GrupoRoute: typeof GrupoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/grupo': {
      id: '/grupo'
      path: '/grupo'
      fullPath: '/grupo'
      preLoaderRoute: typeof GrupoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GrupoRoute: GrupoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
